# Generated by Django 5.1.5 on 2025-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField()),
                ('number2', models.FloatField()),
                ('operator', models.CharField(max_length=10)),
                ('output', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
